vti_encoding:SR|utf8-nl
vti_author:SR|LAN05\\alanb
vti_modifiedby:SR|LAN05\\alanb
vti_timecreated:TR|21 Dec 2003 17:57:56 -0000
vti_timelastmodified:TR|06 Apr 2004 02:57:17 -0000
vti_filesize:IR|7029
vti_extenderversion:SR|4.0.2.8912
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|05 Apr 2004 22:35:49 -0400
vti_cacheddtm:TX|21 Dec 2003 17:57:56 -0000
vti_cachedlinkinfo:VX|
vti_cachedsvcrellinks:VX|
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
