// This file has been autogenerated from a class added in the UI designer.

using System;
using Greeter.Common;
using Greeter.Modules.Pay;
using UIKit;

namespace Greeter
{
    public partial class TabViewController : UITabBarController
    {
        public TabViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();


        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            var item3 = new CheckoutViewController();
            var icon1 = new UITabBarItem(title: "Checkout", image: UIImage.FromBundle(ImageNames.CHECKOUT), null);
            item3.TabBarItem = icon1;
            var controllers = ViewControllers;
            controllers[3] = item3;
            ViewControllers = controllers;
            NavigationController.NavigationBar.Hidden = true;
        }
    }
}
