// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Greeter
{
	public partial class TabViewController : UITabBarController
	{
		public TabViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
