// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace Greeter
{
    public partial class TabViewController : UITabBarController
    {
        public TabViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            NavigationController.NavigationBar.Hidden = true;
        }
    }
}
