//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strive.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Strive.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer App.
        /// </summary>
        internal static string CUSTOMER_APP_TITLE {
            get {
                return ResourceManager.GetString("CUSTOMER_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Password.
        /// </summary>
        internal static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OTP.
        /// </summary>
        internal static string EnterOTP {
            get {
                return ResourceManager.GetString("EnterOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPassword_fpScreen {
            get {
                return ResourceManager.GetString("ForgotPassword_fpScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword_loginScreen {
            get {
                return ResourceManager.GetString("ForgotPassword_loginScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET OTP.
        /// </summary>
        internal static string GetOTP {
            get {
                return ResourceManager.GetString("GetOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        internal static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t receive the OTP?.
        /// </summary>
        internal static string NotReceiveOTP {
            get {
                return ResourceManager.GetString("NotReceiveOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP sent to your registered mobile #.
        /// </summary>
        internal static string OTPSent {
            get {
                return ResourceManager.GetString("OTPSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFY.
        /// </summary>
        internal static string OTPVerify {
            get {
                return ResourceManager.GetString("OTPVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords are not the same.
        /// </summary>
        internal static string PasswordsNotSame {
            get {
                return ResourceManager.GetString("PasswordsNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter registered mobile # to receive OTP.
        /// </summary>
        internal static string ReceiveOTP {
            get {
                return ResourceManager.GetString("ReceiveOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Password?.
        /// </summary>
        internal static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend OTP.
        /// </summary>
        internal static string ResendOTP {
            get {
                return ResourceManager.GetString("ResendOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUp.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tim App.
        /// </summary>
        internal static string TIM_APP_TITLE {
            get {
                return ResourceManager.GetString("TIM_APP_TITLE", resourceCulture);
            }
        }
    }
}
