//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strive.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Strive.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string TIM_APP_TITLE {
            get {
                return ResourceManager.GetString("TIM_APP_TITLE", resourceCulture);
            }
        }
        
        internal static string CUSTOMER_APP_TITLE {
            get {
                return ResourceManager.GetString("CUSTOMER_APP_TITLE", resourceCulture);
            }
        }
        
        internal static string ForgotPassword_loginScreen {
            get {
                return ResourceManager.GetString("ForgotPassword_loginScreen", resourceCulture);
            }
        }
        
        internal static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        internal static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        internal static string ReceiveOTP {
            get {
                return ResourceManager.GetString("ReceiveOTP", resourceCulture);
            }
        }
        
        internal static string ForgotPassword_fpScreen {
            get {
                return ResourceManager.GetString("ForgotPassword_fpScreen", resourceCulture);
            }
        }
        
        internal static string GetOTP {
            get {
                return ResourceManager.GetString("GetOTP", resourceCulture);
            }
        }
        
        internal static string EnterOTP {
            get {
                return ResourceManager.GetString("EnterOTP", resourceCulture);
            }
        }
        
        internal static string OTPVerify {
            get {
                return ResourceManager.GetString("OTPVerify", resourceCulture);
            }
        }
        
        internal static string OTPSentEmail {
            get {
                return ResourceManager.GetString("OTPSentEmail", resourceCulture);
            }
        }
        
        internal static string ResendOTP {
            get {
                return ResourceManager.GetString("ResendOTP", resourceCulture);
            }
        }
        
        internal static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        internal static string PasswordsNotSame {
            get {
                return ResourceManager.GetString("PasswordsNotSame", resourceCulture);
            }
        }
        
        internal static string ReceiveOTPLabel {
            get {
                return ResourceManager.GetString("ReceiveOTPLabel", resourceCulture);
            }
        }
        
        internal static string UsernamePasswordIncorrect {
            get {
                return ResourceManager.GetString("UsernamePasswordIncorrect", resourceCulture);
            }
        }
        
        internal static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        internal static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        internal static string ValidMobile {
            get {
                return ResourceManager.GetString("ValidMobile", resourceCulture);
            }
        }
        
        internal static string ValidName {
            get {
                return ResourceManager.GetString("ValidName", resourceCulture);
            }
        }
        
        internal static string NotReceiveOTP {
            get {
                return ResourceManager.GetString("NotReceiveOTP", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string enterOTPError {
            get {
                return ResourceManager.GetString("enterOTPError", resourceCulture);
            }
        }
        
        internal static string NotRegisteredEmail {
            get {
                return ResourceManager.GetString("NotRegisteredEmail", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string UserId {
            get {
                return ResourceManager.GetString("Employee ID / Email ID ", resourceCulture);
            }
        }
        
        internal static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        internal static string SelectRoleAlert {
            get {
                return ResourceManager.GetString("SelectRoleAlert", resourceCulture);
            }
        }
        
        internal static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        internal static string Washer {
            get {
                return ResourceManager.GetString("Washer", resourceCulture);
            }
        }
        
        internal static string Cashier {
            get {
                return ResourceManager.GetString("Cashier", resourceCulture);
            }
        }
        
        internal static string Detailer {
            get {
                return ResourceManager.GetString("Detailer", resourceCulture);
            }
        }
        
        internal static string FinishBay {
            get {
                return ResourceManager.GetString("FinishBay", resourceCulture);
            }
        }
        
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        internal static string GreetBay {
            get {
                return ResourceManager.GetString("GreetBay", resourceCulture);
            }
        }
        
        internal static string Runner {
            get {
                return ResourceManager.GetString("Runner", resourceCulture);
            }
        }
        
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        internal static string SignUpSuccessful {
            get {
                return ResourceManager.GetString("SignUpSuccessful", resourceCulture);
            }
        }
        
        internal static string SignUpUnSuccessful {
            get {
                return ResourceManager.GetString("SignUpUnSuccessful", resourceCulture);
            }
        }
        
        internal static string LogoutCancelButton {
            get {
                return ResourceManager.GetString("LogoutCancelButton", resourceCulture);
            }
        }
        
        internal static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        internal static string LogoutSuccessButton {
            get {
                return ResourceManager.GetString("LogoutSuccessButton", resourceCulture);
            }
        }
        
        internal static string LogoutTitle {
            get {
                return ResourceManager.GetString("LogoutTitle", resourceCulture);
            }
        }
        
        internal static string EmployeeAppName {
            get {
                return ResourceManager.GetString("EmployeeAppName", resourceCulture);
            }
        }
        
        internal static string OwnerAppName {
            get {
                return ResourceManager.GetString("OwnerAppName", resourceCulture);
            }
        }
        
        internal static string CustomerAppName {
            get {
                return ResourceManager.GetString("CustomerAppName", resourceCulture);
            }
        }
        
        internal static string EmployeePackageName {
            get {
                return ResourceManager.GetString("EmployeePackageName", resourceCulture);
            }
        }
        
        internal static string OwnerPackageName {
            get {
                return ResourceManager.GetString("OwnerPackageName", resourceCulture);
            }
        }
        
        internal static string CustomerPackageName {
            get {
                return ResourceManager.GetString("CustomerPackageName", resourceCulture);
            }
        }
        
        internal static string ValidLastName {
            get {
                return ResourceManager.GetString("ValidLastName", resourceCulture);
            }
        }
    }
}
