image: microsoft/dotnet:latest

stages:
    - build
    - test
    
variables:
    test: "Example.Test"
    
before_script:
    - "cd src"
    - "dotnet restore"
    
build:
    stage:  build
    script:
        - echo "Building"
        - "dotnet build"
        - mkdir build
        - touch build/buildinfo.txt

test:
    stage:  test
    script:
        - echo "Testing"
        - test -f "build/Testinfo.txt"