stages:
    - build
    - test
    
variables:
    PROJECT_NAME: "Admin.API"
    BUILD_IMAGE: "mcr.microsoft.com/dotnet/core/sdk:3.1"
    
before_script:
    - echo "pre script"
    - echo src/Sourcecode/API/Admin.API/$PROJECT_NAME
    - "cd src/Sourcecode/API/Admin.API/$PROJECT_NAME"
    - "dotnet restore"
    
build:
    stage:  build
    image: $BUILD_IMAGE
    script:
        - echo "Building"
        - dotnet build --configuration Release

test:
    stage:  test
    script:
        - echo "Testing"
        - test -f "build/Testinfo.txt"
        
        