CREATE TABLE [Cus].[tblCustomer] (
    [Customerid]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [FirstName]              VARCHAR (32)   NOT NULL,
    [MiddleName]             VARCHAR (32)   NULL,
    [LastName]               VARCHAR (32)   NULL,
    [ContactMail]            VARCHAR (64)   NOT NULL,
    [SSNo]                   VARCHAR (16)   NOT NULL,
    [LocationId]             INT            NOT NULL,
    [Address1]               VARCHAR (100)  NOT NULL,
    [Address2]               VARCHAR (50)   NULL,
    [City]                   VARCHAR (64)   NOT NULL,
    [State]                  VARCHAR (64)   NOT NULL,
    [Zip]                    VARCHAR (12)   NOT NULL,
    [CustomerTypeId]         INT            NOT NULL,
    [CustomerCorpId]         INT            NULL,
    [PrimaryContactNumber]   VARCHAR (14)   NOT NULL,
    [SecondaryContactNumber] VARCHAR (14)   NULL,
    [PrimaryContactType]     VARCHAR (14)   NOT NULL,
    [SecondaryContactType]   VARCHAR (14)   NULL,
    [MailAllowed]            BIT            NOT NULL,
    [CustomerScoreCategory]  CHAR (2)       NULL,
    [NumberofAccounts]       INT            NULL,
    [Notes]                  VARCHAR (8000) NULL,
    [RecordNotes]            VARCHAR (8000) NULL,
    [IsActive]               BIT            NOT NULL,
    [CreatedDate]            DATETIME       CONSTRAINT [DF_tblCustomer_CreatedDate] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_tblCustomer_UserRoleid] PRIMARY KEY CLUSTERED ([Customerid] ASC)
);

