vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|24 Aug 2006 16:42:00 -0000
vti_extenderversion:SR|4.0.2.8912
vti_filesize:IR|7827
vti_backlinkinfo:VX|lubmon/admurledit.asp lubmon/admurleditlistfra.asp
vti_nexttolasttimemodified:TR|22 Feb 2006 16:39:34 -0000
vti_author:SR|IUSR_LAN06
vti_timecreated:TR|22 Feb 2006 16:36:20 -0000
vti_cacheddtm:TX|24 Aug 2006 16:42:00 -0000
vti_cachedlinkinfo:VX|Q|main.css D|admURLEditListFra.ASP D|admURLEditListFra.asp
vti_cachedsvcrellinks:VX|FQUS|main.css FDUS|admURLEditListFra.ASP FDUS|admURLEditListFra.asp
vti_cachedbodystyle:SR|<body class=pgframe>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
