vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|06 Apr 2004 03:11:00 -0000
vti_extenderversion:SR|4.0.2.8912
vti_filesize:IR|3371
vti_backlinkinfo:VX|lubmon/admurl.asp
vti_nexttolasttimemodified:TR|06 Apr 2004 03:11:40 -0000
vti_author:SR|LANDINGTON\\alanb
vti_timecreated:TR|24 Aug 2006 16:42:04 -0000
vti_cacheddtm:TX|06 Apr 2004 03:11:00 -0000
vti_cachedlinkinfo:VX|Q|main.css
vti_cachedsvcrellinks:VX|FQUS|main.css
vti_cachedbodystyle:SR|<body class=pgframe>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
