vti_encoding:SR|utf8-nl
vti_author:SR|LANDINGTON\\alanb
vti_timecreated:TR|08 Oct 2006 23:17:24 -0000
vti_timelastmodified:TR|08 Oct 2006 23:17:00 -0000
vti_filesize:IR|7971
vti_extenderversion:SR|4.0.2.8912
vti_backlinkinfo:VX|
vti_cacheddtm:TX|08 Oct 2006 23:17:00 -0000
vti_cachedlinkinfo:VX|
vti_cachedsvcrellinks:VX|
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
