// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Greeter.Common;
using UIKit;

namespace Greeter.Storyboards
{
    public partial class EmailViewController : BaseViewController
    {
        public EmailViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            AddLeftPadding(tfEmp, UIConstants.TEXT_FIELD_HORIZONTAL_PADDING);
            AddRightPadding(tfEmp, UIConstants.TEXT_FIELD_RIGHT_BUTTON_PADDING);

            AddLeftPadding(tfCust, UIConstants.TEXT_FIELD_HORIZONTAL_PADDING);
            AddRightPadding(tfCust, UIConstants.TEXT_FIELD_RIGHT_BUTTON_PADDING);
        }
    }
}
