// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Greeter.Storyboards
{
	public interface IEmailDelegate
	{
		void SendEmailClicked(string email);
	}

	public partial class EmailPopupViewController : BaseViewController
	{
		public IEmailDelegate EmailDelegate;

		public EmailPopupViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

			btnSend.TouchUpInside += delegate {
				SendEmailCliked(tfEmail.Text);
			};

			btnCancel.TouchUpInside += delegate {
				CloseController();
			};
		}

		void SendEmailCliked(string email)
		{
			if (string.IsNullOrWhiteSpace(email))
			{
				ShowAlertMsg(Common.Messages.EMAIL_MISSING);
				return;
			}

			DismissViewController(true, () => { });
			EmailDelegate?.SendEmailClicked(email);
		}

		void CloseController()
		{
			DismissViewController(true, () => { });
		}
    }
}
