// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Greeter.Storyboards
{
	public partial class ImageController : UIViewController
	{
		public ImageController (IntPtr handle) : base (handle)
		{
		}
	}
}
