// This file has been autogenerated from a class added in the UI designer.

using System;
using Greeter.Cells;
using Greeter.Extensions;
using Greeter.Sources;
using UIKit;

namespace Greeter.Storyboards
{
    public partial class IssuesViewController : UIViewController
    {
        // Data
        const string SCREEN_TITLE = "Issues";

        public IssuesViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            Initialise();
        }

        void Initialise()
        {
            Title = SCREEN_TITLE;
            viewHeader.AddHearderViewShadow();
            tvIssues.RegisterClassForCellReuse(typeof(IssueCell), IssueCell.Key);
            tvIssues.Source = new IssuesSource();
        }
    }
}
