// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Greeter.Common;
using UIKit;

namespace Greeter.Storyboards
{
	public partial class PagerViewController : UIPageViewController, IUIPageViewControllerDataSource
    {
        UIViewController[] vcs;

		public PagerViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var s = UIStoryboard.FromName(StoryBoardNames.HOME, null);
            var vc = s.InstantiateViewController(nameof(ImageController));
            var vc1 = s.InstantiateViewController(nameof(GreenController));
            vcs = new UIViewController[] { vc, vc1 };

            DataSource = this;
        }

        UIViewController IUIPageViewControllerDataSource.GetPreviousViewController(UIPageViewController pageViewController, UIViewController referenceViewController)
        {
            int index = Array.IndexOf(vcs, referenceViewController);
            var previousIndex = index - 1;
            if (previousIndex < 0) return null;
            return vcs[previousIndex];
        }

        UIViewController IUIPageViewControllerDataSource.GetNextViewController(UIPageViewController pageViewController, UIViewController referenceViewController)
        {
            int index = Array.IndexOf(vcs, referenceViewController);
            var nextIndex = index + 1;
            if (nextIndex > vcs.Length - 1) return null;
            return vcs[nextIndex];
        }
    }
}
