// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreAnimation;
using MaterialComponents;
using UIKit;

namespace Greeter.Storyboards
{
    public partial class SampleViewController : UIViewController
	{
        //let usernameTextFieldController: MDCTextInputControllerOutlined;

        //TextInputControllerOutlined textInputControllerOutlined;

        public SampleViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var t = new TextField();
            t.AutocorrectionType = UITextAutocorrectionType.No;
            t.ClearButtonMode = UITextFieldViewMode.Never;
            t.Frame = new CoreGraphics.CGRect(20, 300, 300, 70);

            TextInputControllerUnderline textInputControllerOutlined = new TextInputControllerUnderline(t);
            textInputControllerOutlined.PlaceholderText = "Test Placeholder";
            textInputControllerOutlined.ActiveColor = UIColor.Green;
            textInputControllerOutlined.FloatingPlaceholderActiveColor = UIColor.Brown;


            View.Add(t);

            //var bottomLine = new CALayer();
            //bottomLine.Frame = new CoreGraphics.CGRect(tfField.Bounds.X, tfField.Bounds.Height - 1, tfField.Bounds.Width, 1);
            ////bottomLine.Frame = new CoreGraphics.CGRect(0.0, 75 - 1, 300, 1.0);
            //tfField.Layer.AddSublayer(bottomLine);

            //bottomLine.BackgroundColor = UIColor.Black.CGColor;

            //tfField.BorderStyle = UITextBorderStyle.None;

            //var bottomLine = new UIView();
            //bottomLine.BackgroundColor = UIColor.Black;
            //tfField.Add(bottomLine);
            //bottomLine.LeadingAnchor.ConstraintEqualTo(tfField.LeadingAnchor).Active = true;
            //bottomLine.TrailingAnchor.ConstraintEqualTo(tfField.TrailingAnchor).Active = true;
            //bottomLine.BottomAnchor.ConstraintEqualTo(tfField.BottomAnchor).Active = true;
            //bottomLine.HeightAnchor.ConstraintEqualTo(1).Active = true;

            //let estimatedFrame = ...
            //var textField = new MaterialComponents.TextInputControllerFilled();
            //textField.PlaceholderText = "Phone number";
            //textField.TextInput.Text = "555-555-5555";
            //textField.leadingAssistiveLabel.text = "This is helper text";
            //textField.Si();
            //View.Add(textField);

            //new MaterialComponents.TextInputControllerFilled

            //let estimatedFrame = ...
            //let textField = MDCFilledTextField(frame: estimatedFrame)
            //textField.label.text = "Phone number"
            //textField.placeholder = "555-555-5555"
            //textField.leadingAssistiveLabel.text = "This is helper text"
            //textField.sizeToFit()
            //view.addSubview(textField)
        }
    }
}
