// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using CoreText;
using UIKit;

namespace Greeter.Storyboards
{
	public partial class SampleReadMoreViewController : UIViewController
	{
		public SampleReadMoreViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var font = UIFont.SystemFontOfSize(size: 20f);
            var height = HeightForLabel(lblText.Text, font, width: lblText.Frame.Width);

            if (height > lblText.Frame.Height)
            {
                btnMore.SetTitle("More", UIControlState.Normal);
            }
            else
            {
                btnMore.Hidden = true;
            }

            btnMore.TouchUpInside += delegate {
                if (btnMore.TitleLabel.Text.Equals("more", StringComparison.InvariantCultureIgnoreCase))
                {
                    lblText.Lines = 0;
                    lblText.SizeToFit();
                    btnMore.SetTitle("Less", UIControlState.Normal);
                }
                else
                {
                    lblText.Lines = 2;
                    lblText.SizeToFit();
                    btnMore.SetTitle("More", UIControlState.Normal);
                }
            };
        }

        nfloat HeightForLabel(String text, UIFont font, nfloat width) {

            UILabel label = new UILabel(frame: new CGRect(0, 0, width, float.MaxValue));

            label.Lines = 0;

            label.LineBreakMode = UILineBreakMode.WordWrap;
            label.Font = font;
            label.Text = text;
            label.SizeToFit();

            return label.Frame.Height;
        }
    }
}
