// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MaterialComponents;
using UIKit;
using Xamarin.Essentials;

namespace Greeter.Storyboards
{
	public partial class TestCustomView : UIView
	{
		public TestCustomView (IntPtr handle) : base (handle)
		{
            //BackgroundColor = UIColor.Brown;
            Initialize();
        }

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();
            //BackgroundColor = UIColor.Red;
            //Initialize();
        }

        public override void LayoutSubviews()
        {
            base.LayoutSubviews();
            //BackgroundColor = UIColor.Blue;
        }

        void Initialize()
        {
            var t = new TextField();
            t.AutocorrectionType = UITextAutocorrectionType.No;
            t.ClearButtonMode = UITextFieldViewMode.Never;
            t.Frame = new CoreGraphics.CGRect(this.Bounds.X, this.Bounds.Y, this.Bounds.Width, this.Bounds.Height);

            TextInputControllerUnderline textInputControllerOutlined;
            textInputControllerOutlined = new TextInputControllerUnderline(t);
            textInputControllerOutlined.PlaceholderText = "Test Placeholder";
            textInputControllerOutlined.TextInput.Text = "Something";
            textInputControllerOutlined.ActiveColor = ColorConverters.FromHex("#4A90E2").ToPlatformColor();
            textInputControllerOutlined.FloatingPlaceholderActiveColor = ColorConverters.FromHex("#4A90E2").ToPlatformColor();
            Add(t);

            //var estimatedFrame = 
            //var textField = new TextInputControllerUnderline();
            //textField.TextInput.Text = "Phone number";
            //textField.PlaceholderText = "555-555-5555";
            //Add(textField);
        }
    }
}
