// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Greeter.Storyboards
{
    public partial class VerifyVehicleInfoViewController : UIViewController
    {
        public VerifyVehicleInfoViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            MakecardView(viewCustName);
            MakecardView(viewVehicle);
            MakecardView(viewBarcode);
            MakecardView(viewType);
        }

        void MakecardView(UIView view)
        {
            view.Layer.CornerRadius = 20;
            view.Layer.ShadowColor = UIColor.Gray.CGColor;
            view.Layer.ShadowOffset = new CoreGraphics.CGSize(width: 0, height: 0);
            view.Layer.ShadowRadius = 12;
            view.Layer.ShadowOpacity = 0.7f;
        }
    }
}
