// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using Greeter.Common;
using Greeter.Extensions;
using UIKit;

namespace Greeter.Storyboards
{
    public partial class EmailViewController : BaseViewController, IUIPickerViewDelegate, IUIPickerViewDataSource
    {
        // Data
        const string SCREEN_TITLE = "Email Receipt";
        public string[] data = new string[] {
            "Main Street 1",
            "Main Street 2",
            "Main Street 3"
        };

        //Views
        UIPickerView pv = new UIPickerView();

        public EmailViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            Initialise();

            //Clicks
            btnPay.TouchUpInside += delegate
            {
                NavigateToPayScreen();
            };
        }

        void Initialise()
        {
            Title = SCREEN_TITLE;

            tfEmp.AddLeftPadding(UIConstants.TEXT_FIELD_HORIZONTAL_PADDING);
            tfEmp.AddRightPadding(UIConstants.TEXT_FIELD_RIGHT_BUTTON_PADDING);

            tfCust.AddLeftPadding(UIConstants.TEXT_FIELD_HORIZONTAL_PADDING);
            tfCust.AddRightPadding(UIConstants.TEXT_FIELD_RIGHT_BUTTON_PADDING);

            AddPickerToolbar(tfEmp, tfEmp.Placeholder, PickerDone);
            tfEmp.InputView = pv;

            pv.DataSource = this;
            pv.Delegate = this;
        }

        void PickerDone()
        {
            int pos = (int)pv.SelectedRowInComponent(0);
            tfEmp.Text = data[pos];
        }

        void NavigateToPayScreen()
        {
            UIViewController vc = GetViewController(GetHomeStorybpard(), nameof(PaymentSucessViewController));
            NavigateToWithAnim(vc);
        }

        public nint GetComponentCount(UIPickerView pickerView)
        {
            return 1;
        }

        public nint GetRowsInComponent(UIPickerView pickerView, nint component)
        {
            return data.Length;
        }

        [Export("pickerView:didSelectRow:inComponent:")]
        public void Selected(UIPickerView pickerView, nint row, nint component)
        {

        }

        [Export("pickerView:titleForRow:forComponent:")]
        public string GetTitle(UIPickerView pickerView, nint row, nint component)
        {
            return data[row];
        }
    }
}
