// This file has been autogenerated from a class added in the UI designer.

using System;
using Greeter.Cells;
using Greeter.Extensions;
using Greeter.Sources;
using UIKit;

namespace Greeter.Storyboards
{
    public partial class IssuesViewController : BaseViewController
    {
        // Data
        const string SCREEN_TITLE = "Issues";

        public IssuesViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InitialiseUI();
            UpdateDataToUI();

            btnAddIssue.TouchUpInside += BtnAddIssueTouchUpInside;
        }

        private void BtnAddIssueTouchUpInside(object sender, EventArgs e)
        {
            PresentAddIssuePopUp();
        }

        void PresentAddIssuePopUp()
        {
            UIViewController vc = GetViewController(GetHomeStorybpard(), nameof(AddIssueViewController));
            vc.ModalPresentationStyle = UIModalPresentationStyle.OverCurrentContext;
            PresentViewController(vc, true, null);
        }

        void InitialiseUI()
        {
            NavigationController.NavigationBar.Hidden = false;
            viewHeader.AddHearderViewShadow();
            tvIssues.RegisterNibForCellReuse(IssueCell.Nib, IssueCell.Key);
        }

        void UpdateDataToUI()
        {
            Title = SCREEN_TITLE;
            tvIssues.Source = new IssuesSource();
            tvIssues.ReloadData();
        }
    }
}
