// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using Foundation;
using Greeter.Common;
using Greeter.DTOs;
using Greeter.Extensions;
using Greeter.Modules.Service;
using Greeter.Services.Api;
using Greeter.Storyboards;
using UIKit;

namespace Greeter
{
    public partial class ServiceViewController : BaseViewController, IUITextFieldDelegate
    {
        // Static Data
        readonly UIColor unselectedBtnBgColor = UIColor.FromRGB(204, 255, 248);
        readonly UIColor unselectedBtnTxtColor = UIColor.Black;
        readonly UIColor selectedBtnBgColor = UIColor.FromRGB(1, 100, 87);
        readonly UIColor selectedBtnTxtColor = UIColor.White;

        // State Values
        bool IsWash = true;

        //BarcodeResponse barcodeResponse;

        public ServiceViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            // Initial UI Settings
            Initialise();
            UpdateData();

            //_ = GetAvailableSchedules();

            //Clicks
            btnWash.TouchUpInside += delegate
            {
                IsWash = true;
                UnSelectButton(btnDetail);
                SelectButton(btnWash);
            };

            btnDetail.TouchUpInside += delegate
            {
                IsWash = false;
                UnSelectButton(btnWash);
                SelectButton(btnDetail);
            };

            btnCloseBarcode.TouchUpInside += delegate
            {
                EmptyTextField(txtFieldBarcode);
            };

            btnCancel.TouchUpInside += delegate
            {
                GoBackWithAnimation();
            };

            btnSelect.TouchUpInside += delegate
            {
                if (txtFieldBarcode.Text.IsEmpty())
                {
                    ShowAlertMsg(Common.Messages.BARCODE_EMPTY);
                }
                else
                {
                    _ = GetBarcodeDetails(txtFieldBarcode.Text);
                }
            };

            btnDriveUp.TouchUpInside += delegate
            {
                NavigateToWashOrDetailScreen();
            };

            lblChangeloc.AddGestureRecognizer(new UITapGestureRecognizer(LocationTap));
            lblLastService.AddGestureRecognizer(new UITapGestureRecognizer(LastServiceTap));
            lblViewIssue.AddGestureRecognizer(new UITapGestureRecognizer(ViewIssueTap));
        }

        void UpdateData()
        {
            lblLocName.Text = AppSettings.LocationName;
        }

        //async Task GetAvailableSchedules()
        //{
        //    #if DEBUG
        //        var apiService = new WashApiService();
        //        var getAvailableScheduleReq = new GetAvailableScheduleReq() { LocationId = AppSettings.LocationID };
        //        var availableScheduleResponse = await apiService.GetAvailablilityScheduleTime(getAvailableScheduleReq);
        //    #endif
        //}

        void Initialise()
        {
            txtFieldBarcode.AddLeftPadding(UIConstants.TEXT_FIELD_RIGHT_BUTTON_PADDING);
            txtFieldBarcode.AddRightPadding(UIConstants.TEXT_FIELD_RIGHT_BUTTON_PADDING);

            txtFieldBarcode.WeakDelegate = this;

            lblWashTime.Text = AppSettings.WashTime.ToString() + ":00";
            DismissKeyboardOnTapArround = true;

            #if DEBUG
              //txtFieldBarcode.Text = "ZNL9678";
                txtFieldBarcode.Text = "61012381";
            #endif
        }

        [Export("textFieldShouldReturn:")]
        public bool ShouldReturn(UITextField textField)
        {
            textField.EndEditing(true);
            return true;
        }

        async Task GetBarcodeDetails(string barcode)
        {
            ShowActivityIndicator();
            var response = await new VehicleApiService().GetBarcode(barcode);
            HideActivityIndicator();

            HandleResponse(response);

            if (response.IsSuccess() && response.ClientAndVehicleDetailList != null && response.ClientAndVehicleDetailList.Count > 0)
            {
                //barcodeResponse = response;
                txtFieldBarcode.Text = string.Empty;
                NavigateToWashOrDetailScreen(response.ClientAndVehicleDetailList[0]);
            }
            else
                ShowAlertMsg(Common.Messages.BARCODE_WRONG);
        }

        private void LocationTap()
        {
            UIViewController vc = UIStoryboard.FromName(StoryBoardNames.USER, null)
                                 .InstantiateViewController(nameof(LocationViewController));

            TabBarController.NavigationController.SetViewControllers(new UIViewController[] { vc }, true);
        }

        void LastServiceTap(UITapGestureRecognizer tap)
        {
            if (txtFieldBarcode.Text.IsEmpty())
            {
                ShowAlertMsg(Common.Messages.BARCODE_EMPTY);
                return;
            }

            _ = CheckBarcodeAndNavigateToLastServicecAsync(txtFieldBarcode.Text);
        }

        async Task CheckBarcodeAndNavigateToLastServicecAsync(string barcode)
        {
            var clientAndVehicleDetail = await CheckBarcodeAsync(barcode);
            if (clientAndVehicleDetail is not null)
            {
                txtFieldBarcode.Text = string.Empty;
                NavigateToLastService(clientAndVehicleDetail);
            }
        }

        async Task<ClientAndVehicleDetail> CheckBarcodeAsync(string barcode)
        {
            ShowActivityIndicator();
            var response = await SingleTon.VehicleApiService.GetBarcode(txtFieldBarcode.Text);
            HideActivityIndicator();

            HandleResponse(response);

            ClientAndVehicleDetail clientAndVehicleDetail = null;

            if (response.IsSuccess() && response.ClientAndVehicleDetailList != null && response.ClientAndVehicleDetailList.Count > 0)
            {
                clientAndVehicleDetail = response.ClientAndVehicleDetailList[0];
            }
            else
                ShowAlertMsg(Common.Messages.BARCODE_WRONG);

            return clientAndVehicleDetail;
        }

        void ViewIssueTap()
        {
            //if (txtFieldBarcode.Text.IsEmpty())
            //{
            //    ShowAlertMsg(Common.Messages.BARCODE_EMPTY);
            //    return;
            //}

            NavigateToIssue();
        }

        void NavigateToLastService(ClientAndVehicleDetail clientAndVehicleDetail)
        {
            NavigateToWithAnim(new LastVisitViewController(clientAndVehicleDetail.ClientID, clientAndVehicleDetail.Barcode));
        }

        void NavigateToIssue()
        {
            var vc = this.Storyboard.InstantiateViewController(nameof(IssuesViewController));
            NavigateToWithAnim(vc);
        }

        void NavigateToWashOrDetailScreen(ClientAndVehicleDetail clientDetail = null)
        {
            //if (IsWash)
            //    ShowAlertMsg(btnWash.TitleLabel.Text);
            //else
            //    ShowAlertMsg(btnDetail.TitleLabel.Text);

            //UIStoryboard sb = UIStoryboard.FromName("", null);

            var vc = (ServiceQuestionViewController)this.Storyboard.InstantiateViewController(nameof(ServiceQuestionViewController));

            if (clientDetail != null)
            {
                //var clientDetail = barcodeResponse.ClientAndVehicleDetailList[0];
                vc.Barcode = clientDetail.Barcode;
                vc.MakeID = clientDetail.MakeID;
                vc.ModelID = clientDetail.ModelID;
                vc.Model = clientDetail.Model;

                vc.ColorID = clientDetail.ColorID;
                vc.ClientID = clientDetail.ClientID;
                vc.VehicleID = clientDetail.VehicleID;
                vc.CustName = clientDetail.FirstName + " " + clientDetail.LastName;
                vc.UpchargeID = clientDetail.UpchargeID;
            }

            if (IsWash)
            {
                vc.ServiceType = ServiceType.Wash;
            }
            else
            {
                vc.ServiceType = ServiceType.Detail;
            }

            NavigateToWithAnim(vc);
        }

        void UnSelectButton(UIButton btn)
        {
            btn.BackgroundColor = unselectedBtnBgColor;
            SetTextColor(btn, unselectedBtnTxtColor);
        }

        void SelectButton(UIButton btn)
        {
            btn.BackgroundColor = selectedBtnBgColor;
            SetTextColor(btn, selectedBtnTxtColor);
        }

        void EmptyTextField(UITextField txtField)
        {
            txtField.Text = string.Empty;
        }

        void SetTextColor(UIButton btn, UIColor color)
        {
            btn.SetTitleColor(color, UIControlState.Normal);
        }
    }
}
