// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using Greeter.Common;
using Greeter.DTOs;
using Greeter.Extensions;
using Greeter.Modules.Service;
using Greeter.Services.Network;
using Greeter.Storyboards;
using UIKit;

namespace Greeter
{
    public partial class ServiceViewController : BaseViewController
    {
        // Static Data
        readonly UIColor unselectedBtnBgColor = UIColor.FromRGB(204, 255, 248);
        readonly UIColor unselectedBtnTxtColor = UIColor.Black;
        readonly UIColor selectedBtnBgColor = UIColor.FromRGB(1, 100, 87);
        readonly UIColor selectedBtnTxtColor = UIColor.White;

        // State Values
        bool IsWash = true;

        BarcodeResponse barcodeResponse;

        public ServiceViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            // Initial UI Settings
            txtFieldBarcode.AddLeftPadding(UIConstants.TEXT_FIELD_RIGHT_BUTTON_PADDING);
            txtFieldBarcode.AddRightPadding(UIConstants.TEXT_FIELD_RIGHT_BUTTON_PADDING);

            //Clicks
            //btnBack.TouchUpInside += delegate
            //{
            //    GoBackWithAnimation();
            //};

            btnWash.TouchUpInside += delegate
            {
                IsWash = true;
                UnSelectButton(btnDetail);
                SelectButton(btnWash);
            };

            btnDetail.TouchUpInside += delegate
            {
                IsWash = false;
                UnSelectButton(btnWash);
                SelectButton(btnDetail);
            };

            btnCloseBarcode.TouchUpInside += delegate
            {
                EmptyTextField(txtFieldBarcode);
            };

            btnCancel.TouchUpInside += delegate
            {
                GoBackWithAnimation();
            };

            btnSelect.TouchUpInside += delegate
            {
                if (txtFieldBarcode.Text.IsEmpty())
                {
                    ShowAlertMsg(Common.Messages.BARCODE_EMPTY);
                }
                else
                {
                    _ = GetBarcodeDetails(txtFieldBarcode.Text);
                }
            };

            btnDriveUp.TouchUpInside += delegate
            {
                NavigateToWashOrDetailScreen();
            };

            lblLastService.AddGestureRecognizer(new UITapGestureRecognizer(LastServiceTap));
            lblViewIssue.AddGestureRecognizer(new UITapGestureRecognizer(NavigateToIssue));
        }

        async Task GetBarcodeDetails(string barcode)
        {
            ShowActivityIndicator();
            var response = await new ApiService(new NetworkService()).GetBarcode(barcode);
            HideActivityIndicator();

            if (response.IsNoInternet())
            {
                ShowAlertMsg(response.Message);
                return;
            }

            if (response.IsSuccess() && response.ClientAndVehicleDetailList != null && response.ClientAndVehicleDetailList.Count > 0)
            {
                barcodeResponse = response;
                NavigateToWashOrDetailScreen(true);
            }
            else
                ShowAlertMsg(Common.Messages.BARCODE_WRONG);
        }

        void LastServiceTap(UITapGestureRecognizer tap)
        {
            NavigateToLastService();
        }

        void NavigateToLastService()
        {
            NavigateToWithAnim(new LastVisitViewController());
        }

        void NavigateToIssue()
        {
            var vc = this.Storyboard.InstantiateViewController(nameof(IssuesViewController));
            NavigateToWithAnim(vc);
        }

        void NavigateToWashOrDetailScreen(bool isFromBarcode = false)
        {
            //if (IsWash)
            //    ShowAlertMsg(btnWash.TitleLabel.Text);
            //else
            //    ShowAlertMsg(btnDetail.TitleLabel.Text);

            //UIStoryboard sb = UIStoryboard.FromName("", null);

            var vc = (ServiceQuestionViewController)this.Storyboard.InstantiateViewController(nameof(ServiceQuestionViewController));

            if (isFromBarcode)
            {
                var vehicleDetail = barcodeResponse.ClientAndVehicleDetailList[0];
                vc.Barcode = vehicleDetail.Barcode;
                vc.MakeID = vehicleDetail.MakeID;
                vc.ModelID = vehicleDetail.ModelID;
                vc.Model = vehicleDetail.Model;

                vc.ColorID = vehicleDetail.ColorID;
                vc.ClientID = vehicleDetail.ClientID;
                vc.VehicleID = vehicleDetail.VehicleID;
            }

            if (IsWash)
            {
                vc.ServiceType = ServiceType.Wash;
            }
            else
            {
                vc.ServiceType = ServiceType.Detail;
            }

            NavigateToWithAnim(vc);
        }

        void UnSelectButton(UIButton btn)
        {
            btn.BackgroundColor = unselectedBtnBgColor;
            SetTextColor(btn, unselectedBtnTxtColor);
        }

        void SelectButton(UIButton btn)
        {
            btn.BackgroundColor = selectedBtnBgColor;
            SetTextColor(btn, selectedBtnTxtColor);
        }

        void EmptyTextField(UITextField txtField)
        {
            txtField.Text = string.Empty;
        }

        void SetTextColor(UIButton btn, UIColor color)
        {
            btn.SetTitleColor(color, UIControlState.Normal);
        }
    }
}
