CREATE TABLE [StriveCarSalon].[membershiplist] (
    [Name]                                        NVARCHAR (255) NULL,
    [Car count]                                   FLOAT (53)     NULL,
    [Date]                                        NVARCHAR (255) NULL,
    [All Rows#Method]                             NVARCHAR (255) NULL,
    [Customer Name]                               NVARCHAR (255) NULL,
    [All Rows#Brand]                              NVARCHAR (255) NULL,
    [Last 4]                                      FLOAT (53)     NULL,
    [Substring value]                             NVARCHAR (255) NULL,
    [Amount]                                      MONEY          NULL,
    [All Rows#Status]                             NVARCHAR (255) NULL,
    [Bar Code (Custom Field #0)]                  NVARCHAR (255) NULL,
    [Barcode]                                     NVARCHAR (255) NULL,
    [Make]                                        NVARCHAR (255) NULL,
    [New Model]                                   NVARCHAR (255) NULL,
    [Model (Custom Field #2)]                     NVARCHAR (255) NULL,
    [Color (Custom Field #3)]                     NVARCHAR (255) NULL,
    [Monthly Package (Custom Field #4)]           NVARCHAR (255) NULL,
    [ABB pricing]                                 FLOAT (53)     NULL,
    [Extra Serv]                                  NVARCHAR (255) NULL,
    [All Rows#Vehicle Upcharge (Custom Field #5)] NVARCHAR (255) NULL,
    [Membership price]                            FLOAT (53)     NULL,
    [Membership]                                  NVARCHAR (255) NULL,
    [Car Number]                                  FLOAT (53)     NULL,
    [isDiscount]                                  NVARCHAR (255) NULL,
    [Additional services]                         NVARCHAR (255) NULL,
    [New upcharge]                                NVARCHAR (255) NULL,
    [Upcharges]                                   NVARCHAR (255) NULL,
    [Calculated Upcharge]                         FLOAT (53)     NULL,
    [Addl service price]                          FLOAT (53)     NULL,
    [Upcharge Price]                              FLOAT (53)     NULL,
    [New Total Price]                             FLOAT (53)     NULL,
    [Old New Same]                                NVARCHAR (255) NULL,
    [Difference]                                  NVARCHAR (255) NULL,
    [ClientId]                                    INT            NULL,
    [VehicleId]                                   INT            NULL,
    [Refvehid]                                    INT            NULL,
    [MAKEID]                                      INT            NULL,
    [ModelId]                                     INT            NULL,
    [Colorid]                                     INT            NULL,
    [VehModel]                                    VARCHAR (128)  NULL
);

