CREATE TABLE [StriveCarSalon].[Stg_cashd] (
    [LocationID]     INT             NOT NULL,
    [cashdid]        INT             NOT NULL,
    [ndate]          DATETIME        NOT NULL,
    [DrawerNo]       INT             NULL,
    [CIuserID]       INT             NULL,
    [COUserID]       INT             NULL,
    [Alt_CIuserID]   INT             NULL,
    [Alt_COUserID]   INT             NULL,
    [CIp]            INT             NULL,
    [CIn]            INT             NULL,
    [CId]            INT             NULL,
    [CIq]            INT             NULL,
    [CIh]            INT             NULL,
    [CI1]            INT             NULL,
    [CI5]            INT             NULL,
    [CI10]           INT             NULL,
    [CI20]           INT             NULL,
    [CI50]           INT             NULL,
    [CI100]          INT             NULL,
    [COp]            INT             NULL,
    [COn]            INT             NULL,
    [COd]            INT             NULL,
    [COq]            INT             NULL,
    [COh]            INT             NULL,
    [CO1]            INT             NULL,
    [CO5]            INT             NULL,
    [CO10]           INT             NULL,
    [CO20]           INT             NULL,
    [CO50]           INT             NULL,
    [CO100]          INT             NULL,
    [CITime]         SMALLDATETIME   NULL,
    [COTime]         SMALLDATETIME   NULL,
    [CITotal]        MONEY           NULL,
    [COTotal]        MONEY           NULL,
    [CIRp]           INT             NULL,
    [CIRn]           INT             NULL,
    [CIRd]           INT             NULL,
    [CIRq]           INT             NULL,
    [CORp]           INT             NULL,
    [CORn]           INT             NULL,
    [CORd]           INT             NULL,
    [CORq]           INT             NULL,
    [COChecks]       MONEY           NULL,
    [COCreditCards]  MONEY           NULL,
    [COCreditCards2] MONEY           NULL,
    [COPayouts]      MONEY           NULL,
    [COCreditCards3] MONEY           NULL,
    [COCreditCards4] MONEY           NULL,
    [cd]             MONEY           NULL,
    [cdday]          INT             NULL,
    [bcday]          INT             NULL,
    [amxday]         INT             NULL,
    [dcday]          INT             NULL,
    [dsday]          INT             NULL,
    [md]             MONEY           NULL,
    [pcchrg]         MONEY           NULL,
    [Temp]           DECIMAL (18, 1) NULL,
    [Rain]           INT             NULL,
    [Target]         INT             NULL
);

