CREATE TABLE [StriveCarSalon].[StG_REC] (
    [LocationID]   INT            NOT NULL,
    [recid]        INT            NOT NULL,
    [clientid]     INT            NULL,
    [esttime]      DATETIME       NULL,
    [vehID]        INT            NULL,
    [VehMan]       INT            NULL,
    [VModel]       CHAR (40)      NULL,
    [VehMod]       INT            NULL,
    [VehColor]     INT            NULL,
    [VehMandesc]   VARCHAR (100)  NULL,
    [VehModdesc]   VARCHAR (100)  NULL,
    [VehColordesc] VARCHAR (100)  NULL,
    [datein]       DATETIME       NULL,
    [dateout]      DATETIME       NULL,
    [accamt]       MONEY          NULL,
    [tax]          MONEY          NULL,
    [gtotal]       MONEY          NULL,
    [cashamt]      MONEY          NULL,
    [chargeamt]    MONEY          NULL,
    [cashback]     MONEY          NULL,
    [cardtype]     INT            NULL,
    [totalamt]     MONEY          NULL,
    [PerAdj]       NUMERIC (18)   NULL,
    [Status]       INT            NULL,
    [SalesRep]     INT            NULL,
    [Alt_SalesRep] INT            NULL,
    [Notes]        TEXT           NULL,
    [Line]         INT            NULL,
    [DayCnt]       INT            NULL,
    [cashoutid]    INT            NULL,
    [CardNo]       VARCHAR (20)   NULL,
    [Approval]     VARCHAR (20)   NULL,
    [Signiture]    IMAGE          NULL,
    [CheckAmt]     MONEY          NULL,
    [ChkNo]        CHAR (10)      NULL,
    [ChkPhone]     CHAR (14)      NULL,
    [chkDL]        CHAR (16)      NULL,
    [GiftCardAmt]  MONEY          NULL,
    [GiftCardID]   CHAR (10)      NULL,
    [CloseDte]     SMALLDATETIME  NULL,
    [VINL5]        CHAR (5)       NULL,
    [reg]          TINYINT        NULL,
    [adv]          INT            NULL,
    [QABy]         INT            NULL,
    [estMin]       VARCHAR (50)   NULL,
    [Labor]        DECIMAL (18)   NULL,
    [Review]       INT            NULL,
    [ReviewNote]   VARCHAR (1000) NULL
);

