

export const UrlConfig = {
  totalUrl:
  {
    login: `Auth/Login`,
    getCode: `Admin/Common/GetCodesByCategory/`,
    getEmployees: `Admin/Employee/GetAll`,
    updateEmployees: `Admin/Employee/Save`,
    refreshToken: `Admin/Refresh`,
    getLocation: `Admin/Location/GetAll`,
    updateLocation: `Admin/Location/Save`,
    deleteLocation: `Admin/Location/`,
    getLocationById: `Admin/Location/`,
    getServiceSetup: `Admin/ServiceSetup/GetAll`,
    getServiceType: `Admin/ServiceSetup/GetAllServiceType`,
    addServiceSetup: `Admin/ServiceSetup/Add`,
    updateServiceSetup: `Admin/ServiceSetup/Update`,
    deleteServiceSetup: `Admin/ServiceSetup/Delete`,
    getServiceSetupById: `Admin/ServiceSetup/GetServiceById`,
    getProduct: `Admin/Product/GetAll`,
    getProductById: `Admin/Product/GetProductById`,
    addProduct: `Admin/Product/Add`,
    updateProduct: `Admin/Product/Update`,
    deleteProduct: `Admin/Product/Delete`,
    getVendor: `Admin/Vendor/GetAll`,
    updateVendor: `Admin/Vendor/Save`,
    deleteVendor: `Admin/Vendor/Delete/`,
    getVendorById: `Admin/Vendor/GetVendorById/`,
    getCashRegister: `Admin/CashRegister/GetCashRegisterDetails/`,
    saveCashRegister: `Admin/CashRegister/Save`,
    stateList: `Admin/Common/StateList`,
    countryList: `Admin/Common/CountryList`,
    getEmployeeDetail: `Admin/Employee/GetEmployeeById`,
    deleteEmployee: `Admin/Employee/`,
    getAllRoles: `Admin/Employee/GetAllRoles`,
    getDropdownValue: `Admin/Common/GetCodesByCategory/`,
    getOtpCode: `Auth/SendOTP/`,
    uploadDocument: `Admin/Document/SaveDocument`,
    getAllDocument: `Admin/Document/GetAllDocument/`,
    getDocumentById: `Admin/Document/GetDocumentById/`,
    getWeather: `Admin/Weather/GetWeatherData/`,
    saveWeather: `Admin/Weather/SaveWeatherPrediction`,
    verifyOtp: `Auth/VerfiyOTP/`,
    resetPassword: `Auth/ResetPassword`,
    getAllCollision: `Admin/Collision/GetCollisionByEmpId/`,
    getTargetBusinessData: `Admin/Weather/GetWeatherPrediction/`,
    getClient: `Admin/Client/GetAllClient`,
    updateClient: `Admin/Client/Save`,
    deleteClient: `Admin/Client/`,
    getClientById: `Admin/Client/GetClientById/`,
    getAllVehicle: `Admin/Vehicle/GetAll`,
    deleteDocument: `Admin/Document/`,
    updateVehicle: `Admin/Vehicle/Update`,
    deleteVehicle: `Admin/Vehicle/Delete`,
    getVehicleById: `Admin/Vehicle/GetVehicleById`,
    deleteCollision: `Admin/Collision/Delete/`,
    getDetailCollision: `Admin/Collision/GetCollisionById/`,
    saveCollision: `Admin/Collision/Save`,
    getVehicleColor: `Admin/Vehicle/GetCodeTypeColour`,
    getVehicleMake: `Admin/Vehicle/GetCodeMake`,
    getVehicleModel: `Admin/Vehicle/GetCodeTypeModel`,
    getVehicleUpcharge: `Admin/Vehicle/GetCodeUpcharge`,
    getVehicleId: `Admin/Vehicle/GetVehicleId`,
    getVehicleMembership: `Admin/Vehicle/GetVehicleMembership`,
  }
};
