
--Domesticmake
DECLARE @AMC  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='AMC')
DECLARE @Renault  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Renault')
DECLARE @Eagle  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Eagle')
DECLARE @Buick  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Buick')
DECLARE @Cadillac  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Cadillac')
DECLARE @Checker  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Checker')
DECLARE @Chevrolet  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Chevrolet')
DECLARE @Chrysler  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Chrysler')
DECLARE @Imperial  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Imperial')
DECLARE @DeSoto  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='DeSoto')
DECLARE @Dodge  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Dodge')
DECLARE @RAM  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='RAM')
DECLARE @Edsel  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Edsel')
DECLARE @Fisker  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Fisker')
DECLARE @Karma  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Karma')
DECLARE @Ford  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Ford')
DECLARE @Freightliner  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Freightliner')
DECLARE @Geo  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Geo')
DECLARE @GMC  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='GMC')
DECLARE @Hudson  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Hudson')
DECLARE @Hummer  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Hummer')
DECLARE @Jeep  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Jeep')
DECLARE @Lincoln  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Lincoln')
DECLARE @Mercury  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Mercury')
DECLARE @Merkur  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Merkur')
DECLARE @Nash  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Nash')
DECLARE @Rambler  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Rambler')
DECLARE @Oldsmobile  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Oldsmobile')
DECLARE @Packard  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Packard')
DECLARE @Plymouth  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Plymouth')
DECLARE @Pontiac  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Pontiac')
DECLARE @Asüna  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Asüna')
DECLARE @Saturn  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Saturn')
DECLARE @Studebaker  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Studebaker')
DECLARE @Tesla  INT = (SELECT TOP 1 MakeId FROM tblVehicleMake WHERE MakeValue ='Tesla')


--type
DECLARE @Compactcar INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Compact car')
DECLARE @CompactcrossoverSUV INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Compact crossover SUV')
DECLARE @CompactMPV INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Compact MPV')
DECLARE @Compactpickuptruck INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Compact pickup truck')
DECLARE @CompactSUV INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Compact SUV')
DECLARE @Compactwagoncar INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Compact wagon car')
DECLARE @Coupéutility INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Coupé utility')
DECLARE @Crossover INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Crossover')
DECLARE @Fullsizecar INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Full-size car')
DECLARE @FullsizecrossoverSUV INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Full-size crossover SUV')
DECLARE @Fullsizepickuptruck INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Full-size pickup truck')
DECLARE @FullsizeSUV INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Full-size SUV')
DECLARE @Fullsizevan INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Full-size van')
DECLARE @Fullsizewagoncar INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Full-size wagon car')
DECLARE @Grandtourer INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Grand tourer')
DECLARE @Midsizecar INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Mid-size car')
DECLARE @MidsizecrossoverSUV INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Mid-size crossover SUV')
DECLARE @Midsizepickuptruck INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Mid-size pickup truck')
DECLARE @MidsizeSUV INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Mid-size SUV')
DECLARE @Midsizewagoncar INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Mid-size wagon car')
DECLARE @Minivan INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Minivan')
DECLARE @Musclecar INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Muscle car')
DECLARE @Offroadvehicle INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Off-road vehicle')
DECLARE @PersonalluX$000urycar INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Personal luX-$0.00ury car')
DECLARE @Pickuptruck INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Pick-up truck')
DECLARE @Roadstercar INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Roadster car')
DECLARE @Sportcompactcar INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Sport compact car')
DECLARE @Sportscar INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Sports car')
DECLARE @Subcompactcar INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Subcompact car')
DECLARE @SubcompactcrossoverSUV INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Subcompact crossover SUV')
DECLARE @SubcompactSUV INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Subcompact SUV')
DECLARE @TaX$000icab INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='TaX-$0.00icab')
DECLARE @Unknown INT = (SELECT TOP 1 TypeId FROM tblVehicleType WHERE TypeValue ='Unknown')
Declare @Personalluxurycar int =null
Declare @Taxicab int =null

--model
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Gremlin',@AMC,@Subcompactcar)INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Spirit',@AMC,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Encore',@Renault,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Eagle Vista',@Eagle,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Summit',@Eagle,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Pacer',@AMC,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Alliance',@Renault,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Hornet',@AMC,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Concord',@AMC,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Rebel',@AMC,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Matador',@AMC,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Medallion',@Renault,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Premier',@Eagle,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Vision',@Eagle,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Ambassador',@AMC,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Javelin',@AMC,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Talon',@Eagle,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('AMX',@AMC,@Grandtourer)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Eagle',@AMC,@Crossover)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Wagon',@Eagle,@Crossover)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Vista Wagon',@Eagle,@Crossover)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Summit Wagon',@Eagle,@Crossover)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Apollo',@Buick,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Skyhawk',@Buick,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Somerset',@Buick,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Verano',@Buick,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cascada',@Buick,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Skylark',@Buick,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Special',@Buick,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Century',@Buick,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Skylark',@Buick,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Regal',@Buick,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('LaCrosse',@Buick,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('LaCrosse',@Buick,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Special',@Buick,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('LeSabre',@Buick,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Lucerne',@Buick,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Century',@Buick,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Invicta',@Buick,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Wildcat',@Buick,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Centurion',@Buick,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Super',@Buick,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Roadmaster',@Buick,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Electra',@Buick,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Park Avenue',@Buick,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Estate',@Buick,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Roadmaster Estate',@Buick,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Skylark',@Buick,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Limited',@Buick,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Riviera',@Buick,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Reatta',@Buick,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Terraza',@Buick,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Encore',@Buick,@SubcompactcrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Encore GX',@Buick,@SubcompactcrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Envision',@Buick,@CompactcrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Rendezvous',@Buick,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Rainier',@Buick,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Enclave',@Buick,@FullsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Enclave',@Buick,@MidsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cimarron',@Cadillac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('ATS',@Cadillac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('CT4',@Cadillac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('CT4, CT4-V',@Cadillac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('ELR',@Cadillac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Catera',@Cadillac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('CTS',@Cadillac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('CTS, CTS-V',@Cadillac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('CT5',@Cadillac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Series 60',@Cadillac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Series 61',@Cadillac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Series 65',@Cadillac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Series 62',@Cadillac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('6200',@Cadillac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Calais',@Cadillac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Seville',@Cadillac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('STS',@Cadillac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sedan de Ville',@Cadillac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('DTS',@Cadillac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('XTS',@Cadillac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('CT6',@Cadillac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('CT6, CT6-V',@Cadillac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Coupe de Ville',@Cadillac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Series 60 (Sixty Special)',@Cadillac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Fleetwood Brougham',@Cadillac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Brougham',@Cadillac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Fleetwood',@Cadillac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Series 75',@Cadillac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Fleetwood Limousine',@Cadillac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Fleetwood 75',@Cadillac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Eldorado',@Cadillac,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('XT4',@Cadillac,@CompactSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('SRX',@Cadillac,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('XT5',@Cadillac,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('XT6',@Cadillac,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Escalade',@Cadillac,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Allanté',@Cadillac,@Roadstercar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('XLR',@Cadillac,@Roadstercar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('A1',@Checker,@Taxicab)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('A2',@Checker,@Taxicab)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('A3,',@Checker,@Taxicab)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('A6,',@Checker,@Taxicab)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('A8',@Checker,@Taxicab)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('A9',@Checker,@Taxicab)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('A11',@Checker,@Taxicab)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Superba',@Checker,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Marathon',@Checker,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Aerobus',@Checker,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Vega',@Chevrolet,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Monza',@Chevrolet,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Chevette',@Chevrolet,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Spark',@Chevrolet,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Aveo',@Chevrolet,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sonic',@Chevrolet,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Bolt',@Chevrolet,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Corvair',@Chevrolet,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Lakewood',@Chevrolet,@Compactwagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Chevy II Nova',@Chevrolet,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Citation',@Chevrolet,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cavalier',@Chevrolet,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cobalt',@Chevrolet,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cruze',@Chevrolet,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('HHR',@Chevrolet,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Volt',@Chevrolet,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Chevelle Malibu',@Chevrolet,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Malibu',@Chevrolet,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Corsica',@Chevrolet,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Beretta',@Chevrolet,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Malibu Classic',@Chevrolet,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Malibu Maxx',@Chevrolet,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Epica',@Chevrolet,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('SS',@Chevrolet,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Celebrity',@Chevrolet,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Lumina',@Chevrolet,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Deluxe',@Chevrolet,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Fleetline / Styleline',@Chevrolet,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('150 / 210',@Chevrolet,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Byscaine',@Chevrolet,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Townsman',@Chevrolet,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Brookwood',@Chevrolet,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Bel Air',@Chevrolet,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Parkwood',@Chevrolet,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Nomad',@Chevrolet,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Impala',@Chevrolet,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Impala Limited',@Chevrolet,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('SS',@Chevrolet,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Beauville',@Chevrolet,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Kingswood',@Chevrolet,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Caprice',@Chevrolet,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Monte Carlo',@Chevrolet,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Camaro',@Chevrolet,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Corvette',@Chevrolet,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Lumina APV',@Chevrolet,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Venture',@Chevrolet,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Uplander',@Chevrolet,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Astro',@Chevrolet,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('City Express',@Chevrolet,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Van',@Chevrolet,@Fullsizevan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Express',@Chevrolet,@Fullsizevan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Trax',@Chevrolet,@SubcompactcrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Captiva Sport',@Chevrolet,@CompactcrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Trailblazer',@Chevrolet,@CompactcrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Equinox',@Chevrolet,@MidsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Blazer',@Chevrolet,@MidsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Traverse',@Chevrolet,@FullsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('S-10 Blazer',@Chevrolet,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Blazer',@Chevrolet,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Trailblazer (Blazer trim)',@Chevrolet,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Trailblazer',@Chevrolet,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('K5 Blazer',@Chevrolet,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Blazer',@Chevrolet,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Tahoe',@Chevrolet,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Suburban',@Chevrolet,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('El Camino',@Chevrolet,@Coupéutility)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('LUV',@Chevrolet,@Midsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('S-10',@Chevrolet,@Midsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Colorado',@Chevrolet,@Midsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('SSR',@Chevrolet,@Midsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Advance Design',@Chevrolet,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Task Force',@Chevrolet,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('C/K',@Chevrolet,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Silverado',@Chevrolet,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Silverado Clasic',@Chevrolet,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Avalanche',@Chevrolet,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('PT Cruiser',@Chrysler,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Neon',@Chrysler,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('LeBaron',@Chrysler,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Town and Country',@Chrysler,@Midsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cirrus',@Chrysler,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sebring',@Chrysler,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('200',@Chrysler,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Airstream',@Chrysler,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Airflow',@Chrysler,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Windsor',@Chrysler,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('300',@Chrysler,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Newport',@Chrysler,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Fifth Avenue',@Chrysler,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Concorde',@Chrysler,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('300M',@Chrysler,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Saratoga',@Chrysler,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('New Yorker',@Chrysler,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Imperial',@Chrysler,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('LHS',@Chrysler,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Town and Country',@Chrysler,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cordoba',@Chrysler,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Town and Country',@Chrysler,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Pacifica',@Chrysler,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Voyager',@Chrysler,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Pacifica',@Chrysler,@FullsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Aspen',@Chrysler,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('TC by Maserati',@Chrysler,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Prowler',@Chrysler,@Sportcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Crossfire',@Chrysler,@Sportcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Adventurer',@DeSoto,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Airflow',@DeSoto,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Airstream',@DeSoto,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Custom',@DeSoto,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Deluxe',@DeSoto,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Firedome',@DeSoto,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Firelite',@DeSoto,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Firesweep',@DeSoto,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Powermaster',@DeSoto,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Series K-SA',@DeSoto,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Series SC-SD',@DeSoto,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Series S',@DeSoto,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Omni',@Dodge,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Omni 024',@Dodge,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Charger',@Dodge,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Colt',@Dodge,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Colt Vista',@Dodge,@Crossover)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Colt',@Dodge,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('400',@Dodge,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Dart',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Dart',@Dodge,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Dart',@Dodge,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Aspen',@Dodge,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Aries',@Dodge,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Shadow',@Dodge,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Caliber',@Dodge,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Monaco',@Dodge,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Magnum',@Dodge,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Mirada',@Dodge,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('600',@Dodge,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Spirit',@Dodge,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Coronet',@Dodge,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Diplomat',@Dodge,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Dynasty',@Dodge,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Stratus',@Dodge,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Avenger',@Dodge,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Meadowbrook',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Coronet',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Royal',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Custom Royal',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('La Femme',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Matador',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('330',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('440',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('880',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Polara',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Monaco',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('St. Regis',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Intrepid',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Magnum',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Charger',@Dodge,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Charger',@Dodge,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Challanger',@Dodge,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Challenger',@Dodge,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Daytona',@Dodge,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Stealth',@Dodge,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Avenger',@Dodge,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Super Bee',@Dodge,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Viper',@Dodge,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Caravan',@Dodge,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('C/V',@RAM,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('ProMaster City',@RAM,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('A100',@Dodge,@Fullsizevan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sportsman / Tradesman',@Dodge,@Fullsizevan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Ram Van / Ram Wagon',@Dodge,@Fullsizevan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sprinter',@Dodge,@Fullsizevan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('ProMaster',@RAM,@Fullsizevan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Journey',@Dodge,@MidsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Durango',@Dodge,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Nitro',@Dodge,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Ramcharger',@Dodge,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Durango',@Dodge,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Rampage',@Dodge,@Coupéutility)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('D50',@Dodge,@Compactpickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Ram 50',@Dodge,@Compactpickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Dakota',@Dodge,@Midsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('D-Series',@Dodge,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('RAM',@Dodge,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('1500',@RAM,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('1500 Classic',@RAM,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Ranger',@Edsel,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Pacer',@Edsel,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Corsair',@Edsel,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Citation',@Edsel,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Roundup',@Edsel,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Villager',@Edsel,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Bermuda',@Edsel,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Karma',@Fisker,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Revero',@Karma,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Fiesta',@Ford,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Festiva',@Ford,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Aspire',@Ford,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Falcon',@Ford,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Maverick',@Ford,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Fairmont',@Ford,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Tempo',@Ford,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Contour',@Ford,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Pinto',@Ford,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Escort',@Ford,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Focus',@Ford,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Fairlane',@Ford,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Torino',@Ford,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Gran Torino',@Ford,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('LTD II',@Ford,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Granada',@Ford,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('LTD Fox',@Ford,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Taurus',@Ford,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Fusion',@Ford,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('1941 Ford: Deluxe / Super Deluxe',@Ford,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('1949 Ford: Deluxe / Custom',@Ford,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('1952 Ford: Mainline / Customline / Crestline',@Ford,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Fairlane',@Ford,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Custom 500',@Ford,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Galaxie',@Ford,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('LTD',@Ford,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('LTD Crown Victoria',@Ford,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Crown Victoria',@Ford,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Five Hundred',@Ford,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Taurus',@Ford,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Country Squire',@Ford,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Thunderbird',@Ford,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('EXP',@Ford,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Probe',@Ford,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Mustang',@Ford,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Mustang Mach-E',@Ford,@MidsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('GT',@Ford,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Aerostar',@Ford,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Windstar',@Ford,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Freestar',@Ford,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Freestyle',@Ford,@FullsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Taurus X',@Ford,@FullsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Transit Connect',@Ford,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('C-Max',@Ford,@CompactMPV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('E-Series',@Ford,@Fullsizevan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Transit',@Ford,@Fullsizevan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('EcoSport',@Ford,@SubcompactcrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Edge',@Ford,@MidsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Flex',@Ford,@FullsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Bronco II',@Ford,@CompactSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Escape',@Ford,@CompactSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Explorer',@Ford,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Bronco',@Ford,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Expedition',@Ford,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Excursion',@Ford,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Ranchero',@Ford,@Coupéutility)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Falcon Ranchero',@Ford,@Coupéutility)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Durango',@Ford,@Coupéutility)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Ranger',@Ford,@Compactpickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Explorer Sport Trac',@Ford,@Midsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Ranger',@Ford,@Midsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('F-Series',@Ford,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('F-Series Super Duty',@Ford,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sprint',@Chevrolet,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Metro',@Geo,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Spectrum',@Chevrolet,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Nova',@Chevrolet,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Prizm',@Geo,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Storm',@Geo,@Sportcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Tracker',@Geo,@CompactSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Terrain',@GMC,@MidsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Acadia',@GMC,@FullsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Acadia',@GMC,@MidsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Jimmy',@GMC,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Typhoon',@GMC,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Envoy',@GMC,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Yukon',@GMC,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Yukon XL',@GMC,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Spirit',@GMC,@Coupéutility)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Caballero',@GMC,@Coupéutility)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('S-15',@GMC,@Midsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sonoma',@GMC,@Midsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Syclone',@GMC,@Midsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Canyon',@GMC,@Midsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sierra',@GMC,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sierra Classic',@GMC,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sierra LD',@GMC,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Safari',@GMC,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('G-Series',@GMC,@Fullsizevan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Savana',@GMC,@Fullsizevan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Jet',@Hudson,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Commodore',@Hudson,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Wasp',@Hudson,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Hornet',@Hudson,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Italia',@Hudson,@Grandtourer)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('H1',@Hummer,@Offroadvehicle)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('H2',@Hummer,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('H3',@Hummer,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('CJ',@Jeep,@Offroadvehicle)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Wrangler',@Jeep,@Offroadvehicle)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Renegade',@Jeep,@SubcompactcrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Compass',@Jeep,@CompactcrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Patriot',@Jeep,@CompactcrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Wagonner',@Jeep,@CompactSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cherokee',@Jeep,@CompactSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Liberty',@Jeep,@CompactSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Grand Wagooner',@Jeep,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Grand Cherokee',@Jeep,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Commander',@Jeep,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cherokee',@Jeep,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Wagonner',@Jeep,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Grand Wagonner',@Jeep,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Comanche',@Jeep,@Compactpickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Gladiator',@Jeep,@Midsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Versailles',@Lincoln,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Continental',@Lincoln,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('LS',@Lincoln,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Zephyr',@Lincoln,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('MKZ',@Lincoln,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Lincoln-Zephyr',@Lincoln,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Zephyr',@Lincoln,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('L-Series',@Lincoln,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('K-Series',@Lincoln,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Custom',@Lincoln,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('H-Series',@Lincoln,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('EL-Series',@Lincoln,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cosmopolitan',@Lincoln,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Capri',@Lincoln,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Premiere',@Lincoln,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Continental',@Lincoln,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Town Car',@Lincoln,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('MKS',@Lincoln,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Continental Mark I',@Lincoln,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Continental Mark II',@Lincoln,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Continental Mark III',@Lincoln,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Continental Mark IV',@Lincoln,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Continental Mark V',@Lincoln,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Continental Mark VI',@Lincoln,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Continental Mark VII',@Lincoln,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Continental Mark VIII',@Lincoln,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('MKC',@Lincoln,@CompactcrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Corsair',@Lincoln,@CompactcrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('MKX',@Lincoln,@MidsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Nautilus',@Lincoln,@MidsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('MKT',@Lincoln,@FullsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Aviator',@Lincoln,@FullsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Aviator',@Lincoln,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Navigator',@Lincoln,@FullsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Blackwood',@Lincoln,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Mark LT',@Lincoln,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Bobcat',@Mercury,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Lynx',@Mercury,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Tracer',@Mercury,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Comet',@Mercury,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Zephyr',@Mercury,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Topaz',@Mercury,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Mystique',@Mercury,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Comet',@Mercury,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Montegro',@Mercury,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cougar',@Mercury,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Marquis',@Mercury,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sable',@Mercury,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Montego',@Mercury,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Milan',@Mercury,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Eight',@Mercury,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Monterey',@Mercury,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Montclair',@Mercury,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Meteor',@Mercury,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Meteor',@Mercury,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Park Lane',@Mercury,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Marquis',@Mercury,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Grand Marquis',@Mercury,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Marauder',@Mercury,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Colony Park',@Mercury,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Capri',@Mercury,@Sportcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cougar',@Mercury,@Sportcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cougar',@Mercury,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Villager',@Mercury,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Monterey',@Mercury,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Mariner',@Mercury,@CompactSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Mountaineer',@Mercury,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('M-Series',@Mercury,@Pickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('XR4Ti',@Merkur,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Scorpio',@Merkur,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Metropolitan',@Nash,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Rambler',@Nash,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('American',@Rambler,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Six and V8',@Rambler,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Rebel V8',@Rambler,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Classic',@Rambler,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Marlin',@Rambler,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('600',@Nash,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Statesman',@Nash,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Starfire',@Oldsmobile,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Firenza',@Oldsmobile,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Omega',@Oldsmobile,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cutlass Calais',@Oldsmobile,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Achieva',@Oldsmobile,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Alero',@Oldsmobile,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cutlass',@Oldsmobile,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cutlass Ciera',@Oldsmobile,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Vista Cruiser',@Oldsmobile,@Midsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cutlass Supreme',@Oldsmobile,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Intrigue',@Oldsmobile,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Series 60',@Oldsmobile,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Series 70',@Oldsmobile,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Eighty-Eight',@Oldsmobile,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('LSS',@Oldsmobile,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Ninety-Eight',@Oldsmobile,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Aurora',@Oldsmobile,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Custom Cruiser',@Oldsmobile,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Toronado',@Oldsmobile,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Silhouette',@Oldsmobile,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Bravada',@Oldsmobile,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('110',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Clipper',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('120',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('160',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('180',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Mayfair',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Pacific',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cavalier',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Executive',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Super Eight',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Station Sedan',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Patrician 400',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Patrician',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('400',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Caribbean',@Packard,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Starlight',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Hawk',@Packard,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Horizon',@Plymouth,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Horizon TC3',@Plymouth,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sundance',@Plymouth,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Valiant',@Plymouth,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Volaré',@Plymouth,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Reliant',@Plymouth,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Satellite',@Plymouth,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Fury',@Plymouth,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Caravelle',@Plymouth,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Acclaim',@Plymouth,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Breeze',@Plymouth,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Deluxe / Special Deluxe',@Plymouth,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cranbridge',@Plymouth,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cranbrook',@Plymouth,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Plaza',@Plymouth,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Savoy',@Plymouth,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Belvedere',@Plymouth,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Fury',@Plymouth,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Gran Fury',@Plymouth,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Voyager',@Plymouth,@Fullsizevan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Duster',@Plymouth,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Laser',@Plymouth,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Prowler',@Plymouth,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Barracuda',@Plymouth,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Road Runner',@Plymouth,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Belvedere GTX',@Plymouth,@Musclecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('GTX',@Plymouth,@Musclecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Trailduster',@Plymouth,@MidsizeSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Arrow Duster',@Plymouth,@Midsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Scamp',@Plymouth,@Coupéutility)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Astre',@Pontiac,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Acadian',@Pontiac,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('T1000',@Pontiac,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('LeMans',@Pontiac,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Firefly',@Pontiac,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Wave',@Pontiac,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('G3',@Pontiac,@Subcompactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sunbird',@Pontiac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('J2000',@Pontiac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('2000',@Pontiac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('2000 Sunbird',@Pontiac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sunfire',@Asüna,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Ventura',@Pontiac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Phoenix',@Pontiac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Grand Am',@Pontiac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Tempest',@Pontiac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Vibe',@Pontiac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('G5',@Pontiac,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('LeMans',@Pontiac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Custom S',@Pontiac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Tempest',@Pontiac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Grand Am',@Pontiac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('6000',@Pontiac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('G6',@Pontiac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('G8',@Pontiac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Torpedo',@Pontiac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Chieftain',@Pontiac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Pathfinder',@Pontiac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Strato Chief',@Pontiac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Laurentian',@Pontiac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Catalina',@Pontiac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Parisienne',@Pontiac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Bonneville',@Pontiac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Bonneville',@Pontiac,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Streamliner',@Pontiac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Star Chief',@Pontiac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Star Chief Executive',@Pontiac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Grand Ville',@Pontiac,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Safari',@Pontiac,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Grand Safari',@Pontiac,@Fullsizewagoncar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Grand Prix',@Pontiac,@Personalluxurycar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Solstice',@Pontiac,@Roadstercar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Firebird',@Pontiac,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('GTO',@Pontiac,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Fiero',@Pontiac,@Sportscar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Trans Sport',@Pontiac,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Montana',@Pontiac,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Montana SV6',@Pontiac,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Tracker',@Chevrolet,@SubcompactSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sunrunner',@Asüna,@SubcompactSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Aztek',@Pontiac,@MidsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Torrent',@Pontiac,@MidsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('S-Series',@Saturn,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('ION',@Saturn,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Astra',@Saturn,@Compactcar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('L-Series',@Saturn,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Aura',@Saturn,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('VUE',@Saturn,@CompactcrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Outlook',@Saturn,@FullsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Relay',@Saturn,@Minivan)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sky',@Saturn,@Roadstercar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('President ',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Champion',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Land Cruiser',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Conestoga',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Speedster',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Scotsman',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Golden Hawk',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Silver Hawk',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Sky Hawk',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Flight Hawk',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Power Hawk',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Hawk',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Gran Turismo Hawk',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Lark',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Challenger',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Avanti',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Wagonaire',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Roadster',@Tesla,@Roadstercar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Model 3',@Tesla,@Midsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Model S',@Tesla,@Fullsizecar)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Model Y',@Tesla,@CompactcrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Model X',@Tesla,@FullsizecrossoverSUV)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Comander',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Daytona',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('Cruiser',@Studebaker,@Unknown)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('3500',@RAM,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('2500',@RAM,@Fullsizepickuptruck)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('A4',@Checker,@Taxicab)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('A7',@Checker,@Taxicab)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('A10',@Checker,@Taxicab)
INSERT INTO tblVehicleModel(ModelValue, MakeId,TypeId) values('A12',@Checker,@Taxicab)
