using System;
using System.Collections.Generic;
using System.Text;

namespace Strive.BusinessEntities
{
    public enum SPEnum
    {
        USPLOGIN,
        USPGETUSERBYLOGIN,
        USPGETALLUSERS,
        USPGETALLSERVICETYPE,
        USPGETUSERS,
        USPSAVEUSER,
        USPSAVELOGIN,
        //Employee
        USPGETEMPLOYEE,
        USPSAVEEMPLOYEE,
        USPGETSCHEMABYGUID,
        USPGETCODES,
        USPGETUSERBYAUTHID,
        USPDELETEEMPLOYEE,
        USPGETEMPLOYEEBYEMPID,
        USPGETEMPLOYEEROLES,
        //Document
        USPSAVEDOCUMENT,
        USPGETDOCUMENTBYEMPID,
        USPUPDATEDOCUMENTPASSWORD,
        USPGETALLDOCUMENTBYID,
        //Client
        USPGETALLCLIENT,
        USPDELETECLIENT,
        //Location
        USPGETLOCATION,
        USPSAVELOCATION,
        USPDELETELOCATION,
        USPGETPRODUCT,
        USPDELETEPRODUCT,
        USPGETAllPRODUCT,
        USPGETAllPRODUCTNEW,
        USPGETAllLOCATION,
        USPSaveLOCATION,
        USPGETLOCATIONBYID,
        //Service Setup
        USPGETSERVICE,
        USPSAVESERVICE,
        USPDELETESERVICEBYID,
        USPGETSERVICEBYID,
        //Cash Register
        USPSAVETODAYCASHREGISTER,
        USPGETCASHREGISTERDETAILS,
        USPSAVECASHREGISTERBILLS,
        USPSAVECASHREGISTERCOINS,
        USPSAVECASHREGISTERMAIN,
        USPSAVECASHREGISTEROTHERS,
        USPSAVECASHREGISTERROLES,
        USPSAVECASHREGISTERROLLS,
        USPSAVECASHREGISTER,
        //Collison
        USPGETCOLLISION,
        USPGETCOLLISIONBYID,
        USPSAVECOLLISION,
        USPDELETECOLLISION,
        USPGETALLVENDOR,
        USPSAVEVENDOR,
        USPDELETEVENDOR,
        USPGETVENDORBYID,
        USPGETPASSWORDHASH,
        USPSAVEOTP,
        USPRESETPASSWORD,
        USPSAVECLIENT,
        USPVERIFYOTP,
        USPGETCOLLISIONBYEMPID,
        //MembershipSetup
        USPGETMEMBERSHIPSETUP,
        USPGETSERVICEWITHPRICE,
        USPDELETEMEMBERSHIP,
        USPGETMEMBERSHIPBYID,
        USPSAVEMEMBERSHIPSETUP
    }


}
