

// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Diagnostics;
using Foundation;
using MessageUI;
using UIKit;

namespace Greeter.Storyboards
{
    public partial class PaymentSucessViewController : BaseViewController, IMFMailComposeViewControllerDelegate
    {
        // Data
        const string SCREEN_TITLE = "Pay";

        public long TicketID;
        public string Make;
        public string Model;
        public string Color;
        public string ServiceName;
        public string AdditionalServiceName;
        public float Amount;
        public string CustomerName;
        public bool IsFromNewService = true;

        public PaymentSucessViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            Initialise();
            UpdateData();

            lblReceipt.AddGestureRecognizer(new UITapGestureRecognizer(NoReceiptClicked));

            btnPrint.TouchUpInside += delegate {
                PrintReceipt();
	        };

            btnPrintAndEmail.TouchUpInside += delegate {
                //Todo

                //Print();
            };

            btnEmail.TouchUpInside += delegate {
                SendEmailReceipt();
            };
        }

        void SendEmailReceipt()
        {
            string emailContentHtml = MakeServiceReceipt();
            EmailServiceReceipt(emailContentHtml);
        }

        [Export("mailComposeController:didFinishWithResult:error:")]
        public void Finished(MFMailComposeViewController controller, MFMailComposeResult result, NSError error)
        {
            this.DismissViewController(true, null);
        }

        private void UpdateData()
        {
            lblTicketId.Text = TicketID.ToString();
            lblVehicle.Text = $"{Make} {Model} {Color}";

            var mutableAttributedString = new NSMutableAttributedString(
               "Services: ",
               UIFont.SystemFontOfSize(18));
            var attributedString = new NSAttributedString(
               ServiceName,
               font: UIFont.SystemFontOfSize(18, UIFontWeight.Semibold)
           );

            mutableAttributedString.Append(attributedString);
            lblService.AttributedText = mutableAttributedString;

            lblAmount.Text = $"${Amount}";
        }

        void Initialise()
        {
            NavigationController.NavigationBar.Hidden = false;
            Title = SCREEN_TITLE;
        }

        void NoReceiptClicked(UITapGestureRecognizer tap)
        {
            NavigateToServiceHome();
        }

        void NavigateToServiceHome()
        {
            UIViewController vc = null;
            if (IsFromNewService)
                vc = NavigationController.ViewControllers[NavigationController.ViewControllers.Length - 6];
            else
                vc = NavigationController.ViewControllers[NavigationController.ViewControllers.Length - 3];
            NavigationController.PopToViewController(vc, true);
        }

        string MakeServiceReceipt()
        {
            var body = "<p>Ticket Number : </p>" + TicketID + "<br /><br />";

            if (!string.IsNullOrEmpty(CustomerName))
            {
                body += "<p>Customer Details : </p>" + ""
                    + "<p>Customer Name - " + CustomerName + "</p><br />";
            }

            body += "<p>Vehicle Details : </p>" +
                 "<p>Make - " + Make + "</p>" +
                "<p>Model - " + Model + "</p>" +
                 "<p>Color - " + Color + "</p><br />" +
                 "<p>Services : " + "</p>";

            if (!string.IsNullOrEmpty(ServiceName))
            {
                body += "<p>" + ServiceName + "</p>";
            }

            if (!string.IsNullOrEmpty(AdditionalServiceName) && !AdditionalServiceName.Equals("none", StringComparison.OrdinalIgnoreCase))
            {
                body += "<p>" + AdditionalServiceName + "</p>";
            }

            body += "<br/ ><p>" + "Total Amount : " + Amount.ToString() + "</p>";
            Debug.WriteLine("Email Body :" + body);

            return body;
        }

        void PrintReceipt()
        {
            string printContentHtml = MakeServiceReceipt();
            Print(printContentHtml);
        }
    }
}
