CREATE TABLE [CON].[tblProductTest] (
    [ProductId]           INT                IDENTITY (1, 1) NOT NULL,
    [ProductName]         VARCHAR (50)       NULL,
    [ProductCode]         VARCHAR (10)       NULL,
    [ProductDescription]  VARCHAR (50)       NULL,
    [ProductType]         INT                NULL,
    [ImageFileName]       NVARCHAR (50)      NULL,
    [ImageFilePath]       NVARCHAR (50)      NULL,
    [ThumbFileName]       NVARCHAR (50)      NULL,
    [LocationId]          INT                NULL,
    [VendorId]            INT                NULL,
    [Size]                INT                NULL,
    [SizeDescription]     VARCHAR (10)       NULL,
    [Quantity]            SMALLINT           NULL,
    [QuantityDescription] VARCHAR (10)       NULL,
    [Cost]                DECIMAL (19, 4)    NULL,
    [IsTaxable]           BIT                NULL,
    [TaxAmount]           DECIMAL (19, 4)    NULL,
    [ThresholdLimit]      INT                NULL,
    [IsActive]            BIT                NULL,
    [IsDeleted]           BIT                NULL,
    [CreatedBy]           INT                NULL,
    [CreatedDate]         DATETIMEOFFSET (7) NULL,
    [UpdatedBy]           INT                NULL,
    [UpdatedDate]         DATETIMEOFFSET (7) NULL,
    [Price]               DECIMAL (19, 4)    NULL,
    CONSTRAINT [PK_tblProductTest] PRIMARY KEY CLUSTERED ([ProductId] ASC),
    CONSTRAINT [FK_tblProductTest_LocationId] FOREIGN KEY ([LocationId]) REFERENCES [CON].[tblLocation] ([LocationId]),
    CONSTRAINT [FK_tblProductTest_ProductType] FOREIGN KEY ([ProductType]) REFERENCES [CON].[tblCodeValue] ([id]),
    CONSTRAINT [FK_tblProductTest_Size] FOREIGN KEY ([Size]) REFERENCES [CON].[tblCodeValue] ([id]),
    CONSTRAINT [FK_tblProductTest_VendorId] FOREIGN KEY ([VendorId]) REFERENCES [CON].[tblVendor] ([VendorId])
);

